os:
  - linux

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

services:
  - docker

language: node_js
node_js:
  - "8"

# LATER
# addons:
#   firefox: latest
#   chrome: stable

before_install:
# yarn is outdated on Linux images
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
    export PATH=$HOME/.yarn/bin:$PATH
  fi

install:
- source ./scripts/retry.sh
- retry 3 yarn install

before_script:
- yarn global add surge
# Make variables and function from Travis available in our script
# See implementation https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh
# and http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
- export ANSI_CLEAR
- export -f travis_nanoseconds travis_fold travis_time_start travis_time_finish
# Ensure consecutive Safari sessions don't re-open old tabs
# https://github.com/karma-runner/karma-safari-launcher/issues/6
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    defaults write com.apple.Safari ApplePersistenceIgnoreState YES
  fi
- source ./scripts/blockchain_start.sh

script:
- yarn test
- yarn dist
- yarn build-storybook

after_script:
- source ./scripts/blockchain_stop.sh
- bash ./scripts/publish_docker.sh
- cd dist/ && cp index.html 200.html && cd ..
- source ./config/stagingDeploy.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/

notifications:
  email: false
