os:
  - linux
dist: xenial

# Workaround for Chrome sandboxing issue (https://github.com/travis-ci/travis-ci/issues/8836)
sudo: required

services:
  - docker

language: node_js
node_js:
  - "10"
  - "12"

# LATER
# addons:
#   firefox: latest
#   chrome: stable

install:
- source ./scripts/retry.sh
- retry 3 yarn install

before_script:
# Make variables and function from Travis available in our script
# See implementation https://github.com/travis-ci/travis-build/blob/4041ba116ddb3bdfd66ab8acbb7094dee28d6797/lib/travis/build/templates/header.sh
# and http://www.garbers.co.za/2017/11/01/code-folding-and-timing-in-travis-ci/
- export ANSI_CLEAR
- export -f travis_nanoseconds travis_fold travis_time_start travis_time_finish
# Ensure consecutive Safari sessions don't re-open old tabs
# https://github.com/karma-runner/karma-safari-launcher/issues/6
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    defaults write com.apple.Safari ApplePersistenceIgnoreState YES
  fi
- bash ./scripts/test_start.sh
- export BNS_ENABLED=1
- export CHAINS_ENABLED=1
script:
- TERM=dumb yarn test
- yarn lint
- yarn dist
- yarn build-storybook

after_success:
# Used for ensuring all urls reach app's router in surge 
- cd dist/ && cp index.html 200.html && cd ..
- bash ./scripts/stagingDeploy.sh

after_script:
- bash ./scripts/test_stop.sh
- bash ./scripts/publish_docker.sh

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
  - master
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/

notifications:
  email: false
